### PR TITLE
Reconnect to graphite once per metric

### PR DESCRIPTION
**Pull request by Felixoid**
Currently, the failed process never tries to reconnect. I've implemented one retry per metric with sleeping for one second.

### CODE REVIEW

**Comment by Felixoid** [comment]
Hey, Bernd (@bzed),
Could you take a look here, please? Any concerns against merging it?

*upd*: maybe, it makes sense to make an infinite (or configurable) loop around retries?

**Comment by Felixoid** [comment]
I have changed the logic to retry 3 times with 5s delay and made it configurable, but have not tested it yet. Feel free to review, bu don't merge, please, until `WIP:` will be removed from the topic.

**Comment by bzed** [comment]
I'd do ```time.Sleep(waitRetries * r)``` - otherwise it looks fine, thanks! let me know when its ready to merge.

**Comment by Felixoid** [comment]
Maybe get rid of waitRetries and make it equal to second always? Since it will be progressive, in any case it could be configured quite flexible with connectRetries?

**Comment by bzed** [comment]
Do it! Maybe add some (not too crazy) exponential backoff :)

**Comment by Felixoid** [comment]
Well, it becomes crazy already after 10, I'd say

```
In [1]: a=0 
   ...: for i in range(1, 25): 
   ...:     a += i 
   ...:     print(f'{i} {a}') 
   ...:                                                                                                                                                                                       
1 1
2 3
3 6
4 10
5 15
6 21
7 28
8 36
9 45
10 55
11 66
12 78
13 91
14 105
15 120
16 136
17 153
18 171
19 190
20 210
21 231
22 253
23 276
24 300
```

After last fixes it looks fine:

```
./whisper-to-graphite -basedirectory /whisper -directory /whisper -port 43256 -retries 4 -workers 1 2>&1 | sed 's:/whisper.*\.wsp:metric.wsp:'
2020/01/16 21:25:26 OK: metric.wsp
2020/01/16 21:25:27 OK: metric.wsp
2020/01/16 21:25:28 OK: metric.wsp
2020/01/16 21:25:28 OK: metric.wsp
2020/01/16 21:25:29 OK: metric.wsp
# server is down
2020/01/16 21:25:30 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44212->127.0.0.1:43256: write: broken pipe
2020/01/16 21:25:30 Trying to reconnect and send metric again 3 times
2020/01/16 21:25:30 Sleeping for 1s
2020/01/16 21:25:31 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44212->127.0.0.1:43256: use of closed network connection
2020/01/16 21:25:31 Trying to reconnect and send metric again 2 times
2020/01/16 21:25:31 Sleeping for 2s
2020/01/16 21:25:33 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44212->127.0.0.1:43256: use of closed network connection
2020/01/16 21:25:33 Trying to reconnect and send metric again 1 times
2020/01/16 21:25:33 Sleeping for 3s
2020/01/16 21:25:36 Failed to send metric metric.wsp after 4 retries
2020/01/16 21:25:36 write tcp 127.0.0.1:44212->127.0.0.1:43256: use of closed network connection
2020/01/16 21:25:37 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44212->127.0.0.1:43256: use of closed network connection
2020/01/16 21:25:37 Trying to reconnect and send metric again 3 times
2020/01/16 21:25:37 Sleeping for 1s
2020/01/16 21:25:38 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44212->127.0.0.1:43256: use of closed network connection
2020/01/16 21:25:38 Trying to reconnect and send metric again 2 times
2020/01/16 21:25:38 Sleeping for 2s
2020/01/16 21:25:40 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44212->127.0.0.1:43256: use of closed network connection
2020/01/16 21:25:40 Trying to reconnect and send metric again 1 times
2020/01/16 21:25:40 Sleeping for 3s
# server is back
2020/01/16 21:25:43 OK: metric.wsp
2020/01/16 21:25:44 OK: metric.wsp
2020/01/16 21:25:45 OK: metric.wsp
2020/01/16 21:25:46 OK: metric.wsp
# server is down again
2020/01/16 21:25:47 Failed to send metric metric.wsp to graphite: write tcp 127.0.0.1:44276->127.0.0.1:43256: write: broken pipe
2020/01/16 21:25:47 Trying to reconnect and send metric again 3 times
2020/01/16 21:25:47 Sleeping for 1s
```

And logging on start improved as well

```
2020/01/16 22:02:08 Failed to connect to graphite host with error: dial tcp 127.0.0.1:43256: connect: connection refused
```

**Pull request merged**
